### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by TheNavigat** [scraperlab/browserext#1]
phpbrowser: cannot connect to X server :0.0
No protocol specified

I get that on running the thing.

**Comment by scraperlab** [comment]
You must use Xvfb if your system has not the display. See installation section in README.md.

This error may be if the user has not rights to access the display 0.0.
If your system has the display you may use the xhost utility to set the user rights for the display.

One thing to note, now browserext does not work on 64 bit Linux. It craches with error.

**Comment by TheNavigat** [comment]
I was using Ubuntu 64 bit indeed. I'll try again using a 32 bit virtual machine.
