### ISSUE TITLE
not working  with  windows 2012

### ISSUE THREAD

**Issue by mrqaidi** [scraperlab/browserext#4]
please help i have problem  with installing on windows server 2012. when i add line
extension=php_browserext.dll
![error1](https://cloud.githubusercontent.com/assets/9336767/10459426/b9c687de-71cf-11e5-8fb6-9de8eed5f7df.png)
![error2](https://cloud.githubusercontent.com/assets/9336767/10459425/b9c5e68a-71cf-11e5-8bc7-5ff6f7268a58.png)

please help

**Comment by scraperlab** [comment]
You must copy all dll's from binaries\win32\Qt directory to С:\windows\system32.

**Comment by mrqaidi** [comment]
i did  that . but still not working

**Comment by scraperlab** [comment]
Try to copy this dll's to bin directory of your web server (where the httpd.exe is located, If you use apache).

**Comment by scraperlab** [comment]
Or try to register copied dll's in command line with:
regsvr32 “name.dll”
command
read this http://fix4dll.com/how_to_install_dll_files
