### ISSUE TITLE
issue with centos

### ISSUE THREAD

**Issue by mrqaidi** [scraperlab/browserext#5]
hello i am trying to install this ext on centos i got this error while run ./build.sh

make: g++: Command not found //  fix by yum install gcc-c++
make: **\* [downloader.o] Error 127
make: **\* No rule to make target `/browserext-master/browser/../browserext-static/Linux_Debug/libphpbrowser.a', needed by`browser'.  Stop.

**Comment by mrqaidi** [comment]
after yum install gcc-c++ 

i got this error

In file included from guithread.cpp:1:
phpbrowser.h:7:20: error: QtWebKit: No such file or directory
In file included from guithread.cpp:1:
phpbrowser.h:18: error: expected class-name before ‘{’ token
phpbrowser.h:30: error: ‘QWebFrame’ has not been declared
phpbrowser.h:31: error: ‘QWebFrame’ has not been declared
phpbrowser.h:33: error: ‘QWebFrame’ has not been declared
phpbrowser.h:34: error: ‘QWebFrame’ has not been declared
phpbrowser.h:34: error: ‘NavigationType’ has not been declared
phpbrowser.h:35: error: ‘QWebFrame’ has not been declared
phpbrowser.h:44: error: ‘QWebElement’ does not name a type
phpbrowser.h:56: error: ISO C++ forbids declaration of ‘QWebElement’ with no type
phpbrowser.h:56: error: expected ‘,’ or ‘...’ before ‘&’ token
phpbrowser.h:59: error: ‘QWebElement’ was not declared in this scope
phpbrowser.h:59: error: template argument 1 is invalid
phpbrowser.h:64: error: expected class-name before ‘{’ token
phpbrowser.h:69: error: ‘QWebElement’ has not been declared
phpbrowser.h:84: error: ISO C++ forbids declaration of ‘QWebView’ with no type
phpbrowser.h:84: error: ‘QWebView’ declared as a ‘virtual’ field
phpbrowser.h:84: error: expected ‘;’ before ‘_’ token
phpbrowser.h:85: error: ‘QWebElement’ has not been declared
phpbrowser.h:86: error: ‘QWebElement’ has not been declared
phpbrowser.h:92: error: ISO C++ forbids declaration of ‘QWebElement’ with no type
phpbrowser.h:92: error: expected ‘,’ or ‘...’ before ‘&’ token
phpbrowser.h:93: error: ‘QWebElement’ was not declared in this scope
phpbrowser.h:93: error: template argument 1 is invalid
phpbrowser.h:94: error: ‘QWebElement’ was not declared in this scope
phpbrowser.h:94: error: template argument 1 is invalid
phpbrowser.h:94: error: ‘QWebElement’ has not been declared
phpbrowser.h:95: error: ‘QWebElement’ does not name a type
phpbrowser.h:96: error: ‘QWebElement’ does not name a type
phpbrowser.h:97: error: ‘QWebElement’ has not been declared
phpbrowser.h:112: error: ‘QWebElement’ was not declared in this scope
phpbrowser.h:112: error: template argument 1 is invalid
phpbrowser.h:137: error: ISO C++ forbids declaration of ‘QWebElement’ with no type
phpbrowser.h:137: error: expected ‘,’ or ‘...’ before ‘&’ token
phpbrowser.h:139: error: ‘QWebElement’ does not name a type
phpbrowser.h:145: error: ‘QWebElement’ does not name a type
phpbrowser.h:198: error: ISO C++ forbids declaration of ‘QWebElement’ with no type
phpbrowser.h:198: error: expected ‘,’ or ‘...’ before ‘&’ token
phpbrowser.h:230: error: ‘QWebElement’ has not been declared
make: *_\* [guithread.o] Error 1
make: **\* No rule to make target `/browserext-master/browser/../browserext-static/Linux_Debug/libphpbrowser.a', needed by`browser'.  Stop.
Can't find PHP headers in /usr/include/php
The php-devel package is required for use of this command.
./build.sh: line 15: ./configure: No such file or directory
make: **\* No targets specified and no makefile found.  Stop.

**Comment by scraperlab** [comment]
You need these packages:
gcc-c++
make
php-devel
qt4-devel
qtwebkit-devel
Xvfb

**Comment by scraperlab** [comment]
for qt-4.8.x package you need additional repo:
"Just plop
http://kdeforge.unl.edu/apt/kde-redhat/epel/kde.repo
into /etc/yum.repos.d/
and enable kde-testing and kde-unstable repos

Requires one enable EPEL-6:
http://fedoraproject.org/wiki/EPEL

Optional addons available from:
http://rpmfusion.org/Configuration
"

**Comment by scraperlab** [comment]
http://www.qtcentre.org/threads/56495-How-to-install-4-8-on-CentOS-6

**Comment by scraperlab** [comment]
One note, you must use 32bit Linux, in 64bit Linux browserext crashes.

**Comment by mrqaidi** [comment]
thats bad . i want  use in 64bit

**Comment by scraperlab** [comment]
Now browserext is working in 64-bit Linux too.
