### ISSUE TITLE
Ubuntu 16.04 64bit: stack smashing error on wait

### ISSUE THREAD

**Issue by dogproblems** [scraperlab/browserext#6]
Hi, I was seeing this error when calling the wait method:

```
 *** stack smashing detected ***: /usr/sbin/apache2 terminated
[Fri Jul 29 16:31:33.311719 2016] [core:notice] [pid 15513] AH00051: child pid 15525 exit signal Aborted (6), possible coredump in /etc/apache2

```

After running phpbrowser/test.php through valgrind, it turned out that the problem was on line 394 of phpbrowser/browserext.php. I changed `int sec = 0;` to `long sec = 0;` and the error has gone away.

**Comment by scraperlab** [comment]
fixed
